### ISSUE TITLE
not working in windows

### ISSUE THREAD

**Issue by pavanyogi** [timothycrosley/concentration#10]
C:\Users\Pavan Yogi>concentration improve
Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\concentration.exe\__main__.py", line 9, in <module>
  File "c:\python34\lib\site-packages\hug\api.py", line 391, in __call__
    self.commands.get(command)()
  File "c:\python34\lib\site-packages\hug\interface.py", line 485, in __call__
    result = self.interface(**pass_to_function)
  File "c:\python34\lib\site-packages\hug\interface.py", line 99, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "c:\python34\lib\site-packages\concentration\run.py", line 28, in improve
    with open(settings.HOSTS_FILE, "r+") as hosts_file:
PermissionError: [Errno 13] Permission denied: '/Windows/System32/drivers/etc/hosts'

**Comment by abhinuvpitale** [comment]
I think its supposed to only work for linux, since it uses the etc/hosts. RIght, @timothycrosley ?

**Comment by GreatBahram** [comment]
This is because you need to run that command as admin!
