### ISSUE TITLE
Invalid syntax with asyncio.async

### ISSUE THREAD

**Issue by rodolfo-github** [timothycrosley/concentration#11]
Hi there,
Firstly let me thank you for writing this :+1: 

I can't seem to run concentration because of this error:
```
[test ~]$ ./.local/bin/concentration 
Traceback (most recent call last):
  File "./.local/bin/concentration", line 7, in <module>
    from concentration.run import __hug__
  File "/home/test/.local/lib/python3.7/site-packages/concentration/run.py", line 10, in <module>
    import hug
  File "/home/test/.local/lib/python3.7/site-packages/hug/__init__.py", line 36, in <module>
    from hug import (authentication, directives, exceptions, format, input_format, introspect,
  File "/home/test/.local/lib/python3.7/site-packages/hug/route.py", line 29, in <module>
    import hug.api
  File "/home/test/.local/lib/python3.7/site-packages/hug/api.py", line 37, in <module>
    from hug._async import asyncio, ensure_future
  File "/home/test/.local/lib/python3.7/site-packages/hug/_async.py", line 30
    ensure_future = asyncio.async  # pragma: no cover
                                ^
SyntaxError: invalid syntax
```
I've installed with:
```
[test ~]$ pip -V
pip 18.0 from /usr/lib/python3.7/site-packages/pip (python 3.7)
[test ~]$ pip install --user concentration
Collecting concentration
  Downloading https://files.pythonhosted.org/packages/f8/29/eb2acb729f4197622c2da1c90473431438d9bac18897ddfc05aa1c88dfd1/concentration-1.1.1-py2.py3-none-any.whl
Collecting hug>=2.0.0 (from concentration)
  Downloading https://files.pythonhosted.org/packages/03/69/4987f33c0327bc4550a91858fa7c737ea4516c315801878f48c88921f7a9/hug-2.4.0.tar.gz (68kB)
    100% |████████████████████████████████| 71kB 5.8MB/s 
Collecting falcon==1.4.1 (from hug>=2.0.0->concentration)
  Downloading https://files.pythonhosted.org/packages/e8/d0/20bb807dee65f1f163754670557b128eafce1710f6c9c363a38e357f3783/falcon-1.4.1-py2.py3-none-any.whl (159kB)
    100% |████████████████████████████████| 163kB 10.8MB/s 
Requirement already satisfied: requests in /usr/lib/python3.7/site-packages (from hug>=2.0.0->concentration) (2.19.1)
Collecting python-mimeparse>=1.5.2 (from falcon==1.4.1->hug>=2.0.0->concentration)
  Downloading https://files.pythonhosted.org/packages/26/2e/03bce213a9bf02a2750dcb04e761785e9c763fc11071edc4b447eacbb842/python_mimeparse-1.6.0-py2.py3-none-any.whl
Requirement already satisfied: six>=1.4.0 in /usr/lib/python3.7/site-packages (from falcon==1.4.1->hug>=2.0.0->concentration) (1.11.0)
Requirement already satisfied: chardet>=3.0.2 in /usr/lib/python3.7/site-packages (from requests->hug>=2.0.0->concentration) (3.0.4)
Requirement already satisfied: idna>=2.5 in /usr/lib/python3.7/site-packages (from requests->hug>=2.0.0->concentration) (2.7)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3.7/site-packages (from requests->hug>=2.0.0->concentration) (1.23)
Installing collected packages: python-mimeparse, falcon, hug, concentration
  The scripts falcon-bench and falcon-print-routes are installed in '/home/test/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Running setup.py install for hug ... done
  The script concentration is installed in '/home/test/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed concentration-1.1.1 falcon-1.4.1 hug-2.4.0 python-mimeparse-1.6.0

```

This is under python 3.7.0.
Any ideas?

**Comment by iCart** [comment]
`async` has become a keyword since python 3.7 (possibly 3.6? i'm not sure).
That would explain the issue, but the bug happens in the `hug` library, and is already reported (and fixed) here: https://github.com/timothycrosley/hug/issues/631
Looks like we'll have to wait for another release...

In the meantime, you could either downgrade your python or install the latest version of hug from github.

**Comment by timothycrosley** [comment]
This has since been fixed, thanks for reporting!
